import Head from 'next/head'
import Banner from '../Components/Banner.js'
import Discover from '../Components/Discover.js'
import About from '../Components/About.js'
import Footer from '../Components/Footer'
import Homebanner from '../Components/Homebanner'
import Navbar from '../Components/Navbar'
import Skates from '../Components/Skates'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Your Next Best Skate.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Homebanner />
        <Skates />
        <Discover />
        <About />
        <Banner />
        <Footer />
      </main>
    </div>
  )
}
