import Head from 'next/head'
import Features from '../Components/Features'
import Homebanner from '../Components/Homebanner'
import Navbar from '../Components/Navbar'
import Skates from '../Components/Skates'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Your Next Best Skate.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Homebanner />
        <Skates />
        <Features />
      </main>
    </div>
  )
}
